"""create watchlist entries table

Revision ID: 2cd727eb6185
Revises: a10623f80304
Create Date: 2026-09-25 04:43:19.153198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cd727eb6185'
down_revision: Union[str, Sequence[str], None] = 'a10623f80304'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_identifier', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_entries_entity_identifier'), 'watchlist_entries', ['entity_identifier'], unique=False)
    op.create_index(op.f('ix_watchlist_entries_entity_type'), 'watchlist_entries', ['entity_type'], unique=False)
    op.create_index(op.f('ix_watchlist_entries_is_active'), 'watchlist_entries', ['is_active'], unique=False)
    op.create_index(op.f('ix_watchlist_entries_priority'), 'watchlist_entries', ['priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_entries_priority'), table_name='watchlist_entries')
    op.drop_index(op.f('ix_watchlist_entries_is_active'), table_name='watchlist_entries')
    op.drop_index(op.f('ix_watchlist_entries_entity_type'), table_name='watchlist_entries')
    op.drop_index(op.f('ix_watchlist_entries_entity_identifier'), table_name='watchlist_entries')
    op.drop_table('watchlist_entries')
    # ### end Alembic commands ###
